### ISSUE TITLE
5.4 Merge Actions issue

### ISSUE THREAD

**Issue by GrayJackal** [rionix/GameplayTagsComponent#1]
When trying to compile plugin in 5.4 I get the following:

Unable to merge actions 'UnrealEditor-GameplayTagsComponent.lib' and 'UnrealEditor-GameplayTagsComponent.lib': PrerequisiteItems are different

Plugin was working in 5.2

**Comment by maltsevda** [comment]
Hi, can you explain more about the actions that cause the compilation error? I've checked everything on my machine now: both plugin and project compile. Unreal Engine 5.4.3.
